export enum KeyCodes {
  ENTER = 'Enter',
  ARROW_UP = 'ArrowUp',
  ARROW_DOWN = 'ArrowDown',
};

export enum DateTypes {
  DAY,
  MONTH,
  YEAR,
  HOUR,
  MINUTE,
  SECOND,
}

export const mainDateFormat = 'DD/MMMM/YYYY HH:mm:ss';

export const dateFormats = [
  'D M YY',
  'D MM YY',
  'D MMM YY',
  'D MMMM YY',
  'D M YYYY',
  'D MM YYYY',
  'D MMM YYYY',
  'D MMMM YYYY',
  'DD M YY',
  'DD MM YY',
  'DD MMM YY',
  'DD MMMM YY',
  'DD M YYYY',
  'DD MM YYYY',
  'DD MMM YYYY',
  'DD MMMM YYYY',
  'D M YY HH mm ss',
  'D MM YY HH mm ss',
  'D MMM YY HH mm ss',
  'D MMMM YY HH mm ss',
  'D M YYYY HH mm ss',
  'D MM YYYY HH mm ss',
  'D MMM YYYY HH mm ss',
  'D MMMM YYYY HH mm ss',
  'DD M YY HH mm ss',
  'DD MM YY HH mm ss',
  'DD MMM YY HH mm ss',
  'DD MMMM YY HH mm ss',
  'DD M YYYY HH mm ss',
  'DD MM YYYY HH mm ss',
  'DD MMM YYYY HH mm ss',
  'DD MMMM YYYY HH mm ss',
  'D M YY H mm ss',
  'D MM YY H mm ss',
  'D MMM YY H mm ss',
  'D MMMM YY H mm ss',
  'D M YYYY H mm ss',
  'D MM YYYY H mm ss',
  'D MMM YYYY H mm ss',
  'D MMMM YYYY H mm ss',
  'DD M YY H mm ss',
  'DD MM YY H mm ss',
  'DD MMM YY H mm ss',
  'DD MMMM YY H mm ss',
  'DD M YYYY H mm ss',
  'DD MM YYYY H mm ss',
  'DD MMM YYYY H mm ss',
  'DD MMMM YYYY H mm ss',
  'D M YY H m ss',
  'D MM YY H m ss',
  'D MMM YY H m ss',
  'D MMMM YY H m ss',
  'D M YYYY H m ss',
  'D MM YYYY H m ss',
  'D MMM YYYY H m ss',
  'D MMMM YYYY H m ss',
  'DD M YY H m ss',
  'DD MM YY H m ss',
  'DD MMM YY H m ss',
  'DD MMMM YY H m ss',
  'DD M YYYY H m ss',
  'DD MM YYYY H m ss',
  'DD MMM YYYY H m ss',
  'DD MMMM YYYY H m ss',
  'D M YY H m s',
  'D MM YY H m s',
  'D MMM YY H m s',
  'D MMMM YY H m s',
  'D M YYYY H m s',
  'D MM YYYY H m s',
  'D MMM YYYY H m s',
  'D MMMM YYYY H m s',
  'DD M YY H m s',
  'DD MM YY H m s',
  'DD MMM YY H m s',
  'DD MMMM YY H m s',
  'DD M YYYY H m s',
  'DD MM YYYY H m s',
  'DD MMM YYYY H m s',
  'DD MMMM YYYY H m s',
  'D M YY HH m s',
  'D MM YY HH m s',
  'D MMM YY HH m s',
  'D MMMM YY HH m s',
  'D M YYYY HH m s',
  'D MM YYYY HH m s',
  'D MMM YYYY HH m s',
  'D MMMM YYYY HH m s',
  'DD M YY HH m s',
  'DD MM YY HH m s',
  'DD MMM YY HH m s',
  'DD MMMM YY HH m s',
  'DD M YYYY HH m s',
  'DD MM YYYY HH m s',
  'DD MMM YYYY HH m s',
  'DD MMMM YYYY HH m s',
  'D M YY HH mm s',
  'D MM YY HH mm s',
  'D MMM YY HH mm s',
  'D MMMM YY HH mm s',
  'D M YYYY HH mm s',
  'D MM YYYY HH mm s',
  'D MMM YYYY HH mm s',
  'D MMMM YYYY HH mm s',
  'DD M YY HH mm s',
  'DD MM YY HH mm s',
  'DD MMM YY HH mm s',
  'DD MMMM YY HH mm s',
  'DD M YYYY HH mm s',
  'DD MM YYYY HH mm s',
  'DD MMM YYYY HH mm s',
  'DD MMMM YYYY HH mm s',
];
